# These are supported funding model platforms

github: [JOELwindows7] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: JOELwindows7 # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
ko_fi: JOELwindows7 # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: JOELwindows7 # Replace with a single Liberapay username
# issuehunt: Perkedel/kaded_fnf_mods # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
custom: [https://cointr.ee/joelwindows7, https://github.com/Perkedel/perkedel-astro, https://perkedel.netlify.app/apps/donate] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
